apiVersion: v1
kind: Service
metadata:
  name: coll-f5bdbe5df4ce455da09081b1f078481d-srv
spec:
  selector:
    app: coll-f5bdbe5df4ce455da09081b1f078481d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP